<?php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class formQuestionc extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options = []) : void
    {
       // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('question', TextType::class)
            ->add('choix1', TextType::class)
            ->add('choix2', TextType::class)
            ->add('choix3', TextType::class)
            ->add('choix4', TextType::class);
    }

/*    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ::class,
        ]);
    }*/
}