<?php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormQuestionc extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options = []) : void
    {
       // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('question', TextType::class, ['required' => true, 'attr'=>['placeholder'=>'Question']])
            ->add('choice1', TextType::class, ['required' => true])
            ->add('choice2', TextType::class, ['required' => true])
            ->add('choice3', TextType::class, ['required' => true])
            ->add('choice4', TextType::class, ['required' => true]);
    }

/*    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ::class,
        ]);
    }*/
}